services:
  springboot-app:
    container_name: interview-inside
    image: andreylapynin/interview-inside:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
     - spring.datasource.url=jdbc:postgresql://host.docker.internal:5433/postgres
  db:
    container_name: postgres
    hostname: postgres
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql