services:
  springboot-app:
    container_name: interview-inside
    image: andreylapynin/interview-inside:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
  db:
    container_name: postgres
    hostname: postgres
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: "daakgd5nl6ffvj"
      POSTGRES_USER: "qjbhvhxccrqdat"
      POSTGRES_PASSWORD: "daac57359dc7c73d8652ab3f54605b536b60cbaed4bf40974d5ff641711a6617"
    ports:
      - "5433:5432"